import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Button, Carousel, Footer, SimpleCard } from '@/components'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>TDI Productions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <div className={styles.releaseHero}>
        <h1>Latest Releases</h1>
        <div className={styles.cardGrid}>
          <SimpleCard title="Inside the Tent" image='/thumbnails/insideTheTent.png'/>
          <SimpleCard title="Pigs" image='/thumbnails/pigs.jpg'/>
          <SimpleCard title="Confinement" image='/thumbnails/confinement.jpg'/>
        </div>
        <Link href="/films">
          <Button text='View More' color='primary' width='auto'/>
        </Link>
      </div>
      <div className={styles.aboutHero}>
        <div className={styles.logoContainer}>
          <img src="/tdiLogo.png" alt="tdi productions"/>
        </div>
        <div className={styles.container}>
          <h2>TDI Productions</h2>
          <h1>Twenty Dollar Insurance</h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex repellat perspiciatis vero facere aspernatur ipsum adipisci fugiat non delectus ullam tempore saepe optio soluta, laborum eveniet nihil sequi velit sed?</p>
          <Button text="View Films" color='primary' width='auto' />
        </div>
      </div>
      <Footer />
    </>
  )
}
