import Head from "next/head"
import { Navbar, Footer } from "@/components"

export default function Layout({ children }:any) {
    return (
      <>
        <Head>
          <title>TDI Productions</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </>
    )
  }